# WhatATheme
# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: DK的小站
# Description of the Site
description: 种下一棵树最好的时间是十年前，其次是现在。
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: 博客, 泌尿外科, R语言, 生物信息学
# URL for the Image of custom Favicon
favicon-url: https://s2.loli.net/2024/07/13/DoQZeiLaFgprNt6.png
# 励志的话
motto: "种下一棵树最好的时间是十年前，其次是现在。"
# 首页：欢迎来到我的小站
hero-title: "欢迎来到我的小站"

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: mnwkdengkai@163.com
facebook_username: thedevslot
twitter_username: woodpeckerdk
instagram_username: thedevslot
github_username:  woodpeckerdk
youtube_channel_id: Mrright-je7rc 


# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: DengKai

# Name of the Author
author-name: DengKai
# URL for the Image of the Author
author-image: /assets/images/icon/author_image.jpg
# 60 Words About the Author
author-about: "醉舞经阁半卷书，坐井说天阔。待到囊中羞涩时，怒指乾坤错。  \n欲游山河十万里，伴吾共蹉跎。阅遍天下人无数，知音有几个？"
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/woodpeckerdk

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

